version: '3.8'

services:
  cereal-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7226:7226"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Cereals;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts:/init-scripts
    
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword!
    volumes:
      - ./init-scripts:/init-scripts
    command: >
      bash -c "
        echo 'Waiting for SQL Server to start...'
        sleep 20
        echo 'Running initialization script...'
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrongPassword! -d master -i /init-scripts/init-db.sql
        echo 'Database initialization completed'
      "

volumes:
  sqlserver_data: