# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  cerealapi:
    image: cerealapi
    build:
      context: .
      dockerfile: CerealAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7226:7226
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
